### ISSUE TITLE
Map in evaluate.py

### ISSUE THREAD

**Issue by hannamocha** [stanfordnlp/GloVe#45]
Traceback (most recent call last):
  File "eval/python/evaluate.py", line 110, in <module>
    main()
  File "eval/python/evaluate.py", line 22, in main
    vector_dim = len(vectors[ivocab[0]])
TypeError: object of type 'map' has no len()

Had to put list() around line 16 in evaluate.py in order to fix:
vectors[vals[0]] = list(map(float, vals[1:]))

**Comment by Russell91** [comment]
These changes were to support python 3? Were there any others necessary?

**Comment by hannamocha** [comment]
Yes, they are to support python 3. I don't believe anything else needs to be changed.

**Comment by Russell91** [comment]
Okay, cool. We will look into changing these.

**Comment by hannamocha** [comment]
Oops, found a couple more:

Python 2 to 3 changes:

File: "eval/python/evaluate.py"

Change line 24 to (gets rid of iteritems):
for word, v in vectors.items():

Change line 33 to:
 for i in range(len(filenames)):

Change line 70 to:
for j in range(num_iter):

Change line 78 to:
 for k in range(len(subset)):

**Comment by Xnsam** [comment]
I think this 
for i in range(len(filenames)):
is in line 59...inside the evaluate_vectors(W, vocab, ivocab) function?  isn't it?

**Comment by PursuitYP** [comment]
Thanks a lot! But I think line 33 may should be line 59.
